services:
  - postgres:9.6

variables:
  POSTGRES_DB: spatialspring
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "admin"
  SPRING_CONFIG_LOCATION: classpath:application-test.properties

stages:
  - build_frontend
  - build_backend
  - test_frontend
  - test_backend

build:frontend:
  image: node:latest
  stage: build_frontend
  script: cd frontend && npm install && npm run build
  artifacts:
    name: frontend_build
    paths: 
    - frontend/build/*
    expire_in: 1 week

build:backend:
  image: java:8-jdk
  stage: build_backend
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script: mkdir  backend/src/main/resources/public && cp -r frontend/build/*  backend/src/main/resources/public && cd backend && ./gradlew build 
  artifacts:
    paths:
    - backend/build/libs/
  dependencies:
    - build:frontend

test:backend:
  image: java:8-jdk
  stage: test_backend
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script: cd backend && ./gradlew clean test --info
  artifacts:
    name: reports
    reports:
      junit: backend/build/test-results/TEST-*.xml
    when: always
    expire_in: 1 week

test:frontend:
  image: node:latest
  stage: test_frontend
  script: cd frontend && npm install && npm test

