services:
  - postgres:9.6

variables:
  POSTGRES_DB: spatialspring
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "admin"
  SPRING_CONFIG_LOCATION: classpath:application-test.properties

stages:
  - test_frontend
  - test_backend

test backend:
  image: java:8-jdk
  stage: test_backend
  before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script: cd backend && ./gradlew clean test --info
  artifacts:
    path:
       - backend/build/test-results/TEST-*.xml
    expire_in: 1 week
  artifacts:
    name: reports
    reports:
      junit: backend/build/test-results/TEST-*.xml
    when: always
    expire_in: 1 week

test frontend:
  image: node:latest
  stage: test_frontend
  script: cd frontend && npm install && npm test && npm run build
  artifacts:
    name: frontend_build
    paths: 
    - frontend/build/*
    expire_in: 1 week

