version: '3.3'

# ./gradlew clean build
# docker-compose down
# docker-compose build
# docker-compose up --force-recreate

services:
  database:
    image: kartoza/postgis:9.6-2.4
    ports:
      - "5432:5432"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DBNAME=spatialspring
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=admin

  backend:
    build: ./backend
    ports:
      - "4326:4326"
